# Generated by Django 5.2.10 on 2026-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('reason', models.CharField(blank=True, help_text='任意の理由（例：熊出没、工事中など）', max_length=200)),
            ],
        ),
    ]
