# Generated by Django 5.2.10 on 2026-02-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestrictedGrid',
        ),
    ]
