# Generated by Django 5.2.10 on 2026-01-19 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('gx', models.IntegerField()),
                ('gy', models.IntegerField()),
                ('presence', models.CharField(choices=[('present', 'いた'), ('absent', 'いなかった')], default='absent', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_mode', models.CharField(choices=[('auto', '自動'), ('manual', '手動')], default='auto', max_length=10)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
