# Generated by Django 5.2.10 on 2026-01-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
