# Generated by Django 5.2.10 on 2026-01-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='presence',
            field=models.CharField(choices=[('present', 'いた'), ('absent', 'いなかった')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='species',
            field=models.CharField(blank=True, choices=[('タヌキ', 'タヌキ'), ('キツネ', 'キツネ'), ('シカ', 'シカ'), ('イノシシ', 'イノシシ'), ('サル', 'サル'), ('クマ', 'クマ'), ('不明', 'わからない')], default='不明', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_mode',
            field=models.CharField(choices=[('auto', '自動（現在時刻）'), ('manual', '手動入力')], default='auto', max_length=10),
        ),
    ]
