# Generated by Django 5.2.10 on 2026-02-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_presence_alter_post_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='species',
            field=models.CharField(blank=True, choices=[('タヌキ', 'タヌキ'), ('キツネ', 'キツネ'), ('シカ', 'シカ'), ('イノシシ', 'イノシシ'), ('サル', 'サル'), ('クマ', 'クマ'), ('ハクビシン', 'ハクビシン'), ('アライグマ', 'アライグマ'), ('不明', 'わからない')], default='不明', max_length=50, null=True),
        ),
    ]
