# Generated by Django 5.2.10 on 2026-01-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='puzzles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
