# Generated by Django 5.2.10 on 2026-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consecutive_post_days',
            field=models.IntegerField(default=0, help_text='連続投稿日数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_post_date',
            field=models.DateField(blank=True, help_text='最終投稿日', null=True),
        ),
    ]
