# Generated by Django 5.2.10 on 2026-02-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_consecutive_post_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pioneer_count',
            field=models.IntegerField(default=0, help_text='未開拓エリア(投稿5件以下)への投稿回数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='revival_count',
            field=models.IntegerField(default=0, help_text='1ヶ月以上投稿がなかったエリアへの投稿回数'),
        ),
    ]
