# Generated by Django 5.2.10 on 2026-01-22 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'ordering': ['rarity', 'name'], 'verbose_name': 'トロフィー', 'verbose_name_plural': 'トロフィー'},
        ),
        migrations.AlterModelOptions(
            name='usertrophy',
            options={'ordering': ['-obtained_at'], 'verbose_name': 'ユーザートロフィー', 'verbose_name_plural': 'ユーザートロフィー'},
        ),
        migrations.AddField(
            model_name='trophy',
            name='icon',
            field=models.CharField(default='🏆', help_text='トロフィーのアイコン（絵文字）', max_length=10),
        ),
        migrations.AddField(
            model_name='trophy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='アクティブなトロフィーかどうか'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='condition_type',
            field=models.CharField(help_text="達成条件の種類（例: 'posts_count', 'species_count'）", max_length=50),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='condition_value',
            field=models.PositiveIntegerField(default=1, help_text='達成条件の値'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='description',
            field=models.TextField(help_text='トロフィーの説明'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='name',
            field=models.CharField(help_text='トロフィーの名前', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='rarity',
            field=models.CharField(choices=[('bronze', 'ブロンズ'), ('silver', 'シルバー'), ('gold', 'ゴールド'), ('legend', 'レジェンド')], default='bronze', help_text='トロフィーのレア度', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='obtained_at',
            field=models.DateTimeField(auto_now_add=True, help_text='トロフィー取得日時'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='trophy',
            field=models.ForeignKey(help_text='取得したトロフィー', on_delete=django.db.models.deletion.CASCADE, related_name='user_trophies', to='trophy.trophy'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='user',
            field=models.ForeignKey(help_text='トロフィーを取得したユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL),
        ),
    ]
