# Generated by Django 5.2.10 on 2026-01-22 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0002_alter_trophy_options_alter_usertrophy_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_count', models.PositiveIntegerField(default=0, help_text='いた投稿の総数')),
                ('absent_count', models.PositiveIntegerField(default=0, help_text='いなかった投稿の総数')),
                ('rare_found', models.PositiveIntegerField(default=0, help_text='レア個体発見数')),
                ('user', models.OneToOneField(help_text='ユーザー', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
    ]
