# Generated by Django 5.2.10 on 2026-01-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
