# wildlife/constants.py

GRID_SIZE = 0.0025

CENTER_LAT = 35.66
CENTER_LON = 138.56

HALF_LAT_SPAN = 0.045
HALF_LON_SPAN = 0.09

MIN_LAT = CENTER_LAT - HALF_LAT_SPAN
MIN_LON = CENTER_LON - HALF_LON_SPAN
MAX_LAT = CENTER_LAT + HALF_LAT_SPAN
MAX_LON = CENTER_LON + HALF_LON_SPAN
